//
// Created by User on 16/10/2023.
//

#ifndef TAREAEXTRACLASE3_CYCLICREDUNDANCYCHECK_H
#define TAREAEXTRACLASE3_CYCLICREDUNDANCYCHECK_H


class CRC {

};


#endif //TAREAEXTRACLASE3_CYCLICREDUNDANCYCHECK_H
