//
// Created by User on 16/10/2023.
//

#ifndef TAREAEXTRACLASE3_LONGITUDINALREDUNDANCYCHECK_H
#define TAREAEXTRACLASE3_LONGITUDINALREDUNDANCYCHECK_H


class LRC {

};


#endif //TAREAEXTRACLASE3_LONGITUDINALREDUNDANCYCHECK_H
